export const IPC = {
  snapshotGet: 'snapshot:get',
  projectAdd: 'project:add',
  projectReorder: 'project:reorder',
  projectOpenVSCode: 'project:open-vscode',
  projectOpenFolder: 'project:open-folder',
  sessionCreate: 'session:create',
  sessionRestore: 'session:restore',
  sessionDelete: 'session:delete',
  sessionFirstInput: 'session:first-input',
  themeSet: 'theme:set',
  appInfoGet: 'app:info',
  appUpdateCheck: 'app:update-check',
  appUpdateDownload: 'app:update-download',
  appUpdateCancel: 'app:update-cancel',
  appUpdateInstall: 'app:update-install',
  appOpenLink: 'app:open-link',
  appAutoLaunchGet: 'app:auto-launch-get',
  appAutoLaunchSet: 'app:auto-launch-set',
  terminalWrite: 'terminal:write',
  terminalResize: 'terminal:resize',
  stateChanged: 'state:changed',
  terminalData: 'terminal:data',
  terminalExit: 'terminal:exit',
  appUpdateProgress: 'app:update-progress'
} as const
